### ISSUE TITLE
[PE-D][Tester C] Incorrect labelling of section number in UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W09-3/tp#228]
## Incorrect labelling of section number

![image.png](https://raw.githubusercontent.com/hongshenggg/ped/main/files/4c199b64-80ee-488c-81c2-707fc84a1124.png)

As shown above in the image the `Quick Start` section is labelled as section number 3, however in the UG it is actually section number 2, shown below.

![image.png](https://raw.githubusercontent.com/hongshenggg/ped/main/files/2e869b3d-fef3-4f9d-b195-7569487ad2d2.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: hongshenggg/ped#1

**Comment by cydtseng** [comment]
fixed
