### ISSUE TITLE
[PE-D][Tester E] Uniqueness of email and phone number fields

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W09-3/tp#239]
The app does not check that emails and phone numbers are unique between patient records. I managed to edit it such that two persons have the same email and phone number.

These screenshots are of two different patient records since they have different addresses

![java_gqG5919lZz.png](https://raw.githubusercontent.com/rexcyrio/ped/main/files/90458d9f-e2f4-4f47-ac2b-13066a22e27c.png)

![java_CPIfqdm3Tw.png](https://raw.githubusercontent.com/rexcyrio/ped/main/files/961d4b11-1ab7-4487-8edd-382adf951eab.png)

Expected: the app should check for unique emails and phone numbers since two patients can't share the same email address + phone number

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: rexcyrio/ped#3

**Comment by cydtseng** [comment]
ignoring
