### ISSUE TITLE
[PE-D][Tester A] No command to switch list

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W09-3/tp#240]
There is no command to switch from patient records to drug inventory or hospital hotlines and vice versa. 

This violates the constraint `Typing-Preferred` in the specification, and forces the user to use his/her mouse to switch between patient list, drug inventory and hospital hotlines.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: Skeltons/ped#5

**Comment by Jiayan-Lim** [comment]
Thanks for pointing that out! But due to the limitation of v1.4, since we're not allowed to fix feature flaws, we decide to include this as an enhancement in DG/good-to-have feature for future implementation.
