### ISSUE TITLE
[PE-D][Tester E] Wrong error message for `p view -i` and `d view -i` commands

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W09-3/tp#243]
When I typed in `p view -i abcd`, it shows the error message for the delete command instead. 

Expected: error message for invalid patient index "abcd"

![java_QMpj6mJcEJ.png](https://raw.githubusercontent.com/rexcyrio/ped/main/files/88d4a5e4-bb7a-49bd-98c9-8886a6f0220a.png)

-----

EDIT: this bug is also present in the drugs inventory

![image.png](https://raw.githubusercontent.com/rexcyrio/ped/main/files/6a57c6d1-909d-4251-9b84-455484163d3a.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: rexcyrio/ped#4

**Comment by Emrysil** [comment]
fixed together with #232
