### ISSUE TITLE
[PE-D][Tester A] Unable to add patients who share the same name but different IC

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W09-3/tp#246]
People who share the same name but have different IC are considered 2 unique people. However, the program does not recognize that and only allows one of them to exist in the patient records.

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: Skeltons/ped#6

**Comment by Jiayan-Lim** [comment]
Thanks for pointing that out! But due to the limitation of v1.4, since we're not allowed to fix feature flaws, we decide to include this as an enhancement/good to have for future implementation.
