### ISSUE TITLE
[PE-D][Tester E] Incorrect error message for "too high a drug storage count"

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W09-3/tp#250]
Following the user guide section **4.3 Drug Commands Add a drug entry: d add**, when I run the following example command:

```text
d add -tn Panadol -ai Paracetamol -dir Adults and children above 12 years old, 1-2 capsules every 4-6 hours -pur treat fever, headache, toothache, rheumatic and muscle pains -se dizziness, fatigue -sc 500
```

it shows me this:

![image.png](https://raw.githubusercontent.com/rexcyrio/ped/main/files/ea7b9083-6bdf-4603-85ff-e5c5cc835675.png)

However, 500 is at least 1 digit long and is NOT more than 3 digits long, but the app still rejected the value

<br>

Upon changing to 499, it changes to say that the drug already exists:

![image.png](https://raw.githubusercontent.com/rexcyrio/ped/main/files/2abb74bc-7be7-4c41-b3d4-f4a769cb0e56.png)

Expected: error message telling me "too high a drug storage count" for storage count >= 500

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: rexcyrio/ped#5

**Comment by Emrysil** [comment]
Fixed by Nevin
